"""The fixed Covermail v1 HPKE Base ciphersuite wrapper."""

from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives.asymmetric import x25519
from cryptography.hazmat.primitives.hpke import AEAD, KDF, KEM, Suite

from covermail.address.canonical import decode_base64url
from covermail.address.fingerprint import address_digest
from covermail.address.schema import Address
from covermail.errors import DecryptionError
from covermail.protocol.outer_frame import outer_header

HPKE_INFO_LABEL = b"covermail/hpke/v1\x00"
HPKE_SUITE = Suite(KEM.X25519, KDF.HKDF_SHA256, AEAD.AES_128_GCM)
HPKE_ENCAPSULATED_KEY_BYTES = 32
HPKE_TAG_BYTES = 16


def hpke_info(address: Address) -> bytes:
    return HPKE_INFO_LABEL + address_digest(address) + outer_header(address)


def _public_key(address: Address) -> x25519.X25519PublicKey:
    recipient = address["recipient"]
    if not isinstance(recipient, dict) or not isinstance(recipient.get("hpke_public_key"), str):
        raise TypeError("address must be validated before HPKE use")
    raw = decode_base64url(recipient["hpke_public_key"])
    return x25519.X25519PublicKey.from_public_bytes(raw)


def encrypt_inner(address: Address, inner: bytes) -> bytes:
    """Encrypt with a fresh ephemeral X25519 key generated by cryptography."""
    return HPKE_SUITE.encrypt(inner, _public_key(address), info=hpke_info(address))


def decrypt_inner(
    address: Address,
    private_key: x25519.X25519PrivateKey,
    hpke_blob: bytes,
) -> bytes:
    """Authenticate and decrypt, intentionally collapsing all failures."""
    try:
        return HPKE_SUITE.decrypt(hpke_blob, private_key, info=hpke_info(address))
    except (InvalidTag, ValueError) as error:
        raise DecryptionError(
            "not an authentic message for the selected Covermail Address"
        ) from error
